spring:
  profiles:
    active: development
  application:
    name: event-processor
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0 
  zipkin:
    baseUrl: http://zipkin:9411/    
    
server:
  port: 8007    
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod     
---
spring:
  profiles: development
  cloud:
    stream:
      kafka:            
        binder:
          brokers:
          - localhost:9092
        bindings:
          calculator-in:
            destination: expressionpair
            contentType: 'application/json'
          calculator-out:
            destination: hashmap
            contentType: application/json                  
  redis:
    host: localhost
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 7 
        max-idle: 7
        min-idle: 2
        max-wait: -1ms            
                 
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8101/eureka}
---
spring:
  profiles: streams
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - 9.20.194.143:32200
          configuration:
            "[security.protocol]": SASL_SSL
            "[sasl.protocol]": TLSv1.2
            "[ssl.truststore.location]": /data/es-cert.jks
            "[ssl.truststore.password]": xxx
            "[sasl.mechanism]": PLAIN
            "[sasl.jaas.config]": org.apache.kafka.common.security.plain.PlainLoginModule required username="token" password="iNTmxlO56CU_eWtkFbOZWQURwE4CXy-ZYG_MN1bp7XVf";                      
        bindings:
          calculator-in:
            destination: expressionpair
            contentType: 'application/json'
          calculator-out:
            destination: hashmap
            contentType: application/json
  redis:
    host: redis-ibm-redis-ha-dev-master-svc
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 7 
        max-idle: 7
        min-idle: 2
        max-wait: -1ms             

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery:8101/eureka}   
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - kafka-service:9092                      
        bindings:
          calculator-in:
            destination: expressionpair
            contentType: 'application/json'
          calculator-out:
            destination: hashmap
            contentType: application/json
  redis:
    host: redis
    port: 9001
    password: 
    lettuce:
      pool:
        max-active: 7 
        max-idle: 7
        min-idle: 2
        max-wait: -1ms             

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery:8101/eureka}    