apiVersion: v1
kind: Service
metadata:
  name: basic-op-divide
  namespace: <PROJECT>
  labels:
    app: basic-op-divide     
spec:
  type: ClusterIP
  ports:
  - name: "8004"
    port: 8004
    targetPort: 8004
  selector:
    app: basic-op-divide