spring:
  profiles:
    active: default
  application:
    name: event-processor
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0 
  zipkin:
    baseUrl: http://zipkin:9411/
  cloud:
    stream:
      kafka:            
        binder:
          brokers:
          - localhost:9092
        bindings:
          calculator-in:
            destination: expressionpair
            contentType: 'application/json'
          calculator-out:
            destination: hashmap
            contentType: application/json   
  redis:
    host: redis
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 7 
        max-idle: 7
        min-idle: 2
        max-wait: -1ms             
    
server:
  port: 8007    
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod