apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: processor
  namespace: <PROJECT>
  labels:
    app: processor
spec:
  replicas: 1
  strategy: 
    type: Recreate  
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - image: <CONTAINER>
        name: processor
        imagePullPolicy: Always
        ports:
        - containerPort: 8006
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator
            port: 8006
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8006
          initialDelaySeconds: 60
          timeoutSeconds: 10          
        resources:
          requests:
            cpu: 20m
            memory: 50Mi           
      restartPolicy: Always