apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: eventprocessor
  name: eventprocessor
  namespace: <PROJECT>
spec:
  output:
    to:
      kind: ImageStreamTag
      name: eventprocessor:latest
  runPolicy: Serial
  source:
    contextDir: 4.x/apps/Calculator-Spring-Boot/eventprocessor/
    git:
      ref: master
      uri: <GITHUBREPO>
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./docker/Dockerfile
    type: Source
