apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: add
  name: add
  namespace: calculator
spec:
  replicas: 1
  selector:
    deploymentconfig: add
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: add
        deploymentconfig: add       
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/calculator/add
        imagePullPolicy: Always
        name: add
        ports:
        - containerPort: 8001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"         
        resources:         
          requests:
            cpu: 20m
            memory: 50Mi 
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - add
      from:
        kind: ImageStreamTag
        name: add:latest
        namespace: calculator
    type: ImageChange
  - type: ConfigChange      
---
apiVersion: v1
kind: Service
metadata:
  name: basic-op-add
  namespace: calculator
  labels:
    app: basic-op-add
  annotations:
    prometheus.io/scrape: 'true' 
    prometheus.io/path: '/actuator/prometheus'     
spec:
  type: ClusterIP
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    app: basic-op-add
