apiVersion: v1
kind: Service
metadata:
  labels:
    app: processor
  name: processor
  namespace: <PROJECT>
spec:
  ports:
  - name: 8006-tcp
    port: 8006
    protocol: TCP
    targetPort: 8006
  selector:
    app: processor
  type: ClusterIP
