apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: composite-op
  name: composite-op
  namespace: <PROJECT>
spec:
  output:
    to:
      kind: ImageStreamTag
      name: composite-op:latest
  runPolicy: Serial
  source:
    contextDir: 4.x/apps/ppc64le/Calculator-Spring-Boot/composite-op/
    git:
      ref: master
      uri: <GITHUBREPO>
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile
    type: Source
