apiVersion: v1
kind: Service
metadata:
  name: basic-op-subtract
  namespace: <PROJECT>
  labels:
    app: basic-op-subtract     
spec:
  type: ClusterIP
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8002
  selector:
    app: basic-op-subtract