apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
    region: us-south
    zone: sjc03
  name: mysql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-vpc-block-retain-10iops-tier
