apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
    name: client
  selector:
    app: mysql