apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: add
  name: add
  namespace: <PROJECT>
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: <DOCKERREPOSITORY>
  tags:
  - items:
    tag: latest
