apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: multiply
  name: multiply
  namespace: <PROJECT>
spec:
  output:
    to:
      kind: ImageStreamTag
      name: multiply:latest
  runPolicy: Serial
  source:
    contextDir: 4.x/apps/ppc64le/Calculator-Spring-Boot/basic-op-multiply/
    git:
      ref: master
      uri: <GITHUBREPO>
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./docker/Dockerfile
    type: Source
